"""
UnicodeArt 配置模块包
"""

from .constants import (
    # 默认参数值
    DEFAULT_FONT_REDUCE,
    DEFAULT_WIDE_CHAR_RATIO,
    DEFAULT_MATRIX_SIZE,
    DEFAULT_VERTICAL_HORIZONTAL_RATIO,
    MAX_SUM_DATA,
    PIXEL_MAX_VALUE,
    
    # 默认字符集
    DEFAULT_CHARSET,
    WIDE_CHAR_PATTERN,
    
    # 插值算法
    INTERPOLATION_MAP,
    DEFAULT_INTERPOLATION,
    
    # 字体样式
    FONT_STYLE_SUFFIX,
    WINDOWS_FONT_DIR,
    
    # 日志配置
    DEFAULT_LOG_LEVEL,
)

__all__ = [
    'DEFAULT_FONT_REDUCE',
    'DEFAULT_WIDE_CHAR_RATIO',
    'DEFAULT_MATRIX_SIZE',
    'DEFAULT_VERTICAL_HORIZONTAL_RATIO',
    'MAX_SUM_DATA',
    'PIXEL_MAX_VALUE',
    'DEFAULT_CHARSET',
    'WIDE_CHAR_PATTERN',
    'INTERPOLATION_MAP',
    'DEFAULT_INTERPOLATION',
    'FONT_STYLE_SUFFIX',
    'WINDOWS_FONT_DIR',
    'DEFAULT_LOG_LEVEL',
]
